AllCops:
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/initializers/*'
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
   Enabled: false
