AllCops:
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
    - 'db/*'
    - 'config/initializers/_*'
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.3

Rails:
  Enabled: true
#
#Metrics/LineLength:
#  Max: 120
#  Exclude:
#    - 'config/initializers/devise.rb'
#
#Metrics/MethodLength:
#  Max: 15
#
#Metrics/AbcSize:
#  Enabled: false
#
#Style/Documentation:
#  Enabled: false
#
#Style/Encoding:
#  Enabled: false
#
#Style/SignalException:
#  Enabled: false
#
#Style/MultilineMethodCallIndentation:
#  Enabled: false
