production:
  adapter: postgresql
  database: flashcards_production
  host: localhost
  username: ad
  password: "111"
  encoding: utf8

development:
  adapter: postgresql
  database: flashcards_development
  host: localhost
  username: ad
  password: "111"
  encoding: utf8

test:
  adapter: postgresql
  database: flashcards_test
  host: localhost
  username: ad
  password: "111"
  encoding: utf8
